"""create invoice_records table

Revision ID: 3ac8570c78e4
Revises: 
Create Date: 2026-09-29 15:19:56.156925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac8570c78e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('FETCHED', 'PARSED', 'VALIDATED', 'SAVED', 'FAILED', name='invoicerecordstatus', native_enum=False), nullable=False),
    sa.Column('vendor_email', sa.String(), nullable=True),
    sa.Column('actual_content', sa.Text(), nullable=True),
    sa.Column('parsed_content', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_records_process_id'), ['process_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_records_process_id'))

    op.drop_table('invoice_records')
    # ### end Alembic commands ###
